@startuml
UserService->ApplicationEventPublisher: publishEvent(event)
activate ApplicationEventPublisher
ApplicationEventPublisher->UserEventListener: onUserCreated(event)
activate UserEventListener

UserService<--ApplicationEventPublisher
deactivate ApplicationEventPublisher
@enduml