server:
  port: 8888

spring:
  profiles:
    active: native
  security:
    user:
      name: bob
      password: secret
  cloud:
    config:
      server:
        native:
          searchLocations:
            - classpath:/apps
            - classpath:/apps/{application}
            - classpath:/apps/{application}/{profile}
