spring:
  application:
    name: client
  profiles:
    active: prod
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      username: bob
      password: secret
      fail-fast: true
      retry:
        max-attempts: 10
        initial-interval: 2000
        max-interval: 5000
